project:
  type: website
  output-dir: docs

website:
  title: "ideeas lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: ideeas-lab-members.qmd
        text: Members
      - href: onboard-info.qmd
        text: Onboarding
      - href: ug-projects.qmd
        text: "UG Projects"
      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



