---
title: "About"
---

In the IDEEAS Lab, our research focuses on the development and application of data science, machine learning, and natural language processing methods to support engineering education teaching and research. We are particularly interested in the use of these methods to improve the decisions throughout engineering education agents and systems. Right now some of those areas include assessment, engineering ethics, and environmental sustainability education, but we are always looking for new areas to explore and cooking up ideas.

Some of our funded work includes:

* [CAREER: Minds and Machines: Exploring Engineering Faculty Member Mental Models of Generative AI and Instructional Decisions](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2339702&HistoricalAwards=false)

* [Design for Sustainability: How Mental Models of Social-Ecological Systems Shape Engineering Design Decisions](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2300977&HistoricalAwards=false) 

* [Collaborative Research: Research: Intersections between Diversity, Equity, and Inclusion (DEI) and Ethics in Engineering](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2027486&HistoricalAwards=false)

* [EAGER: Natural Language Processing for Teaching and Research in Engineering Education](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2107008&HistoricalAwards=false)

* [Research: Faculty Assessment Mental Models in Engineering Education](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2113631&HistoricalAwards=false)


You will find more information about other ongoing research projects here soon...