---
title: "Lab Members"
format: html
---

## Lab PI: Andrew Katz


### Short Narrative Bio

Dr. Katz is an assistant professor in the Department of Engineering Education at Virginia Tech. He leads the Improving Decisions in Engineering Education Agents and Systems (IDEEAS) Lab. In order to make this slightly less bizarre, I am going to stop the third person narrative, be realistic, and switch to first person.

I completed my PhD in the School of Engineering Education at Purdue University in spring of 2019. I was there for two years after having actually started my doctoral studies at Virginia Tech in Fall 2015. My advisor was Dr. Donna Riley, so when she moved to Purdue to lead the School of Engineering Education there I moved along with her. I was fortunate enough to be supported by an NSF graduate research fellowship, which made the transition a little more feasible since that funding tends to be tied to the student fellow rather than their particular institution of study. For that project (and my dissertation), I studied engineering faculty member mental models of engineering ethics education. I had started graduate school interested in student moral development, but within the first month of the program realized that if faculty members do not change then any sweet research I did on students may not amount to anything. Consequently, I switched to studying faculty members. These days I tend to have an interest in both faculty members and students and go wherever the research problem suggests.

Before starting starting my doctoral work in engineering education, I bounced around a little more than some people. For example, I taught physics (AP Physics I, AP Physics C Mechanics and E&M) at a high school in Dallas, Texas for a couple of years. Before that, I worked as an environmental engineer in Research Triangle Park, NC helping research and write air pollution regulations. That was preceded by a short stint in the Gillings School of Global Public Health at UNC where I was studying health effects of inhalation exposure to small particles in exhaust gas. Of course, I was interested in that from my master's degree in environmental engineering at Texas A&M University, where I focused more on water pollution and epigenetic effects of exposure to endocrine disrupting compounds. I also hold a bachelor's degree in chemical and biomolecular engineering from Tulane University.


## <u>Graduate Students</u>

<br/>


### Name: Isil Anakok
<u>Background</u>: Isil holds a B.S. in Mechatronics Engineering from Kocaeli University in Turkey, and a M.S. in Mechanical Engineering from Virginia Tech. Before she joined Virginia Tech, she worked as an R&D Engineer in wood industry for two years. She worked as a Graduate Teaching Assistant and taught Mechanical Engineering Lab courses for three years. Currently, she is a PhD candidate in Engineering Education at Virginia Tech. She has been working as a Graduate Assistant in the Office of Recruitment, Diversity, and Inclusion. She is a Diversity Scholar and was inducted to the Bouchet Honor Society in 2022.  She has been contributing to various projects related to engineering ethics education, natural language processing, service learning, and diversity, equity, and inclusion. <br/>
<u>Research interests</u>: Engineering ethics, engineering design, service learning, DEI <br/>
<u>Dissertation topic</u>: Engineering ethics <br/>
<u>Contact information</u>: ianakok at vt dot edu <br/>
<u>Twitter</u>: @isilanakok <br/>
[Linkedin](www.linkedin.com/in/isilanakok) <br/>
[Google Scholar](https://scholar.google.com/citations?user=lEtuHMQAAAAJ&hl=en&oi=ao) <br/>
[ORCID](https://orcid.org/0000-0002-1572-8024) <br/>
<u>Personal website</u>: https://isilanakok.github.io/ <br/>


<br/>
<br/>



### Name: Yasir Gamieldien
<u>Background</u>: Yasir is currently a PhD candidate in The Department of Engineering Education at Virginia Tech. He has a BSc in Chemical Engineering in 2013 and a Postgraduate Certificate in Education in 2018 from the University of Cape Town in South Africa. He has worked in Control Engineering in the Petrochemical Industry after graduating until 2016 before pursuing a career in education. While studying to be a high school mathematics and physical sciences teacher, Yasir spent a year teaching English in Japan. Upon returning to South Africa Yasir taught high school physical sciences from 2018 to 2021 before joining the engineering education program at Virginia Tech. <br/>
<u>Research interests</u>: Teaching and Learning, Metacognition, Self-Regulated Learning, Natural Language Processing.<br/>
<u>Dissertation topic</u>: Self-regulated learning during a first year engineering ill-structured problem solving course. <br/>
<u>Contact information</u>: yasirg at vt dot edu <br/>
[Personal website](https://yasirg90.github.io/)

<br/>
<br/>
<br/>



### Name: Tina Griesinger
<u>Background</u>: Engineering educator  <br/>
<u>Research interests</u>: Sustainability, remote teaching and learning, engineering for all <br/>
<u>Dissertation topic</u>: Students’ interests in pursuing careers in sustainability <br/>
<u>Contact information</u>: tgriesinger at vt dot edu <br/>
[LinkedIn](https://www.linkedin.com/in/tina-griesinger-109b4429) <br/>
[ORCID](https://orcid.org/0000-0001-5313-5265) <br/>


<br/>
<br/>


### Name: Amanda Ross
<u>Background</u>: Before joining ENGE and VT in the fall of 2021, Amanda completed her B.S. in mathematics and computer science with a minor in statistics from UMBC in spring 2021. While at UMBC, she also pursued her interests in education by being part of the Sherman Scholars program. Through this program, she worked in Baltimore City public schools, helping to teach math and computer science to students in grades 5-12.<br/>
<u>Research interests</u>: Computer science education, pedagogy, curriculum design and development, student experiences (with a focus on introductory courses) <br/>
<u>Dissertation topic</u>: Undecided <br/>
<u>Contact information</u>: amandaross at vt dot edu <br/>
[LinkedIn](https://www.linkedin.com/in/amanda-ross-040993163/)


<br/>
<br/>


### Name: Umair Shakir
<u>Background</u>: Umair holds bachelor's and master's in civil engineering (University of Engineering Technology, Lahore, Pakistan, and will hold Ph.D. Engineering Education, Virginia Tech, USA [expected in Spring  2023]). He has ten years of professional experience ranging from professional engineer in the National Engineering Services Pakistan (5 years), to Dubai (1-years), and to assistant professor (The University of Lahore-3 years). He is also certified as a Project Management Professional (PMP). During his Ph.D., Umair has served as a graduate research assistant on NSF projects and as a teaching assistant in the Department of Engineering Education at VT. He has analytical skills in python and R. In addition to this, he is currently using the state of the art natural language processing (NLP) techniques to analyze large-scale qualitative data. Ultimately, Umair aspires to serve a leadership role as an international development sector agent, contributing to both educational physical infrastructure and evidenced-based national educational policy. 
<br/>
<u>Research interests</u>: Equity of educational opportunities regardless of class, gender, religion, or location; engineering ethics; program assessment; corruption in the construction industry 
<br/>
<u>Dissertation topic</u>: NLP and engineering ethics assessment 
<br/>
[LinkedIn](www.linkedin.com/in/umair-shakir)

<br/>
<br/>
<br/>

## Undergraduate Students

<br/>

### Name: Rachel Inamn
<u>Background</u>: Rachel is currently pursuing a bachelor's degree in public and urban affairs with a minor in landscape architecture. She is in her first year of the accelerated master's program in urban and regional planning at Virginia Tech. She hopes to work with the federal government as a community planner or transportation analyst with a focus on sustainability and accessibility.
<br/>
<u>Research interests</u>: Sustainability, smart cities, transportation efficiency, data analytics
<br/>
<u>Contact</u>: Racheli at vt dot edu